###
GET http://localhost:9000/api/category


###
GET http://localhost:9000/api/category/64192e0cb03b244e02f4b733


###
POST http://localhost:8000/api/category
Content-Type: application/json

{
  "CategoryName": "women's clothing"
}


###
PUT http://localhost:8000/api/category/64191d4a2ff572ceddd1133e
Content-Type: application/json

{
  "CategoryName": ""
}


###
DELETE http://localhost:8000/api/category/64191467a9769edcf0656d0e
