###
GET http://localhost:8000/api/product


###
POST http://localhost:8000/api/product
Content-Type: application/json

{
"title": "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
"price": 109.95,
"description": "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
"categoryId": "64192e0cb03b244e02f4b733",
"image": "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
"rating": {
"rate": 3.9,
"count": 120
}
},



###
PUT http://localhost:8000/api/product/6418e5c4a4e517d0a1522f59
Content-Type: application/json




###
DELETE http://localhost:8000/api/product/6418e4ffaf505ca3edf2f892