###
get http://localhost:9000/api/user

###

get http://localhost:9000/api/user/get/6412884a91bfaba1c144a612

###
post https://mongodbexpress-kypi.onrender.com/api/user/signup
Content-Type: application/json

{
    "name":"ochko",
    "isAdmin":false,
    "email":"ochko04300@gmail.com",
    "password":"Ochko0424"
}
###
put http://localhost:9000/api/user/update/64128c689d2c005077eadfb5
Content-Type: application/json

{
    "name":"Test15"
}

###
DELETE http://localhost:9000/api/user/delete/641bb2a50be60d985971c336

###
post https://mongodbexpress-kypi.onrender.com/
Content-Type: application/json

{
"email":"ochko0422@gmail.com",
    "password":"Ochko0421"
}
